title: Zirui Wang
tagline: Finance PhD student at UT Austin
logo: /assets/img/profile.jpg
description: Zirui is a first-year Finance PhD student at McCombs School of Business, University of Texas at Austin.
theme: jekyll-theme-minimal
