title: Zirui Wang
logo: /assets/img/profile.jpg
description: Finance Ph.D. Student at McCombs School of Business, University of Texas at Austin [Link to another page](./another-page.html).
theme: jekyll-theme-minimal
